apiVersion: v1
kind: Pod
metadata: 
  name: db-pod
  labels:
    environment: staging
    db: mysql

spec:
  containers:
    - name: db-container
      image: "mysql"
      ports:
        - containerPort: 3306 
      env:
        - name: MYSQL_USER
          value: "spandan"
        - name: MYSQL_PASSWORD
          value: "Spandan10#"
        - name: MYSQL_ROOT_PASSWORD
          value: "admin2005"