apiVersion: v1
kind: Service
metadata: 
  name: nodeport-service
spec:
  type: NodePort
  selector:
    environment: staging
    region: ap-south-1
    az: ap-south-1a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007