apiVersion: v1
kind: Pod
metadata:
  name: my-httpd-container
  labels:
    environment: staging
    app: httpd  
spec: 
  containers:
   - name: my-httpd-container
     image: httpd
     ports: 
      - containerPort: 80
