apiVersion: v1
kind: Pod
metadata:
  name: my-httpd-container
  labels:
    environment: staging
    app: httpd  
spec: 
  containers:
   - name: my-httpd-container
     image: "vimal13/apache-webserver-php"
     ports: 
      - containerPort: 80
     env:
      - name: x
        value: "5"