apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc-app
  labels: 
    app: mynginxapp
    tier: frontend-app
spec:
  template:
    metadata: 
      name: myrc-app
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector: 
    app: mynginxapp
    tier: frontend-app