apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-rc
spec: 
  replicas: 2  
  selector:
    environment: staging
    region: Mumbai
    az: ap-south-1

  template:
    metadata:
      name: my-rc-pod
      labels:
        environment: staging
        region: Mumbai
        az: ap-south-1

    spec: 
      containers:
        - name: rc-app
          image: "vimal13/apache-webserver-php"
          ports:
            - containerPort: 80


