apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec: 
  replicas: 2
  selector:
    matchExpressions:
      - { key: environment, operator: In, values: [staging] }
      - { key: az, operator: In, values: [ap-south-1] }
  template:
    metadata:
      name: my-rs-pod
      labels:
        environment: staging
        az: ap-south-1

    spec:
      containers:
        - name: my-rs-container
          image: "vimal13/apache-webserver-php"
          ports: 
            - containerPort: 80